### ISSUE TITLE
Do not log Traceback when failed to find DB

### ISSUE THREAD

**Issue by thiagodasilva** [swiftstack/1space#161]
Currently when sync starts, if the containers described in the config file are not yet created, the sync will start dumping a lot of exceptions to the log file:

ERROR:s3-sync:Failed to process AUTH_تcct/keystone2a with SyncContainer
ERROR:s3-sync:Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_crawler/__init__.py", line 204, in call_handle_container
    self.handle_container(handler)
  File "/usr/local/lib/python2.7/dist-packages/container_crawler/__init__.py", line 169, in handle_container
    broker_info = broker.get_info()
  File "/usr/local/src/swift/swift/container/backend.py", line 500, in get_info
    with self.get() as conn:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/src/swift/swift/common/db.py", line 375, in get
    raise DatabaseConnectionError(self.db_file, "DB doesn't exist")
DatabaseConnectionError: DB connection error (/swift/nodes/1/node/sdb1/containers/310/192/4db9a0473f6ba06a7d1f7d6627e4a192/4db9a0473f6ba06a7d1f7d6627e4a192.db, 0):
DB doesn't exist

We should limit these logs

**Comment by thiagodasilva** [comment]
The logs are actually coming from container-crawler: https://github.com/swiftstack/container-crawler/blob/master/container_crawler/__init__.py#L214
